#!/usr/bin/env bash
## Manages manage_my_process (start, stop, restart) using PID file /tmp/my_process.pid
if [ "$1" = "start" ]; then 
	./manage_my_process &  
	echo $! > /tmp/my_process.pid
	echo "manage_my_process started" 	

elif [ "$1" = "stop" ]; then 
	kill $(cat /tmp/my_process.pid)
	rm  -f /tmp/my_process.pid
	echo "manage_my_process stopped"

elif [ "$1" = "restart" ]; then 
	kill -TERM $(cat /tmp/my_process.pid)
        rm -f /tmp/my_process.pid
	./manage_my_process &
	echo $! > /tmp/my_process.pid
	echo "manage_my_process restarted"

else 
	echo "Usage: manage_my_process {start|stop|restart}"; exit 1; 
fi
