#!/usr/bin/env bash
# Bash script that: file PID; DSP "To infi.."; DSP "I hate.." SIGTERM; DSP "Y U .." SIGINT; RM SIGQUIT or SIGTERM
echo $$ > /tmp/myscript.pid  
trap 'echo "I hate the kill command"; rm -f /tmp/myscript.pid; exit' SIGTERM 
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -f /tmp/myscript.pid' SIGQUIT 
  
while true;do echo "To infinity and beyond";sleep 2; done
